apiVersion: v1
kind: Service
metadata:
  name: bookbnb-frontend-service
  labels:
    run: bookbnb-frontend-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: frontend-port
  selector:
    app: bookbnb-frontend
